/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i client_adaptor.h -a client_adaptor com.skype.api.client.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CLIENT_ADAPTOR_H_1190747308
#define CLIENT_ADAPTOR_H_1190747308

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "client_adaptor.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.Skype.API.Client
 */
class ClientAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.Skype.API.Client")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.Skype.API.Client\" >\n"
"    <method name=\"Notify\" >\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"message\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ClientAdaptor(QObject *parent);
    virtual ~ClientAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    Q_NOREPLY void Notify(const QString &message);
Q_SIGNALS: // SIGNALS
};

#endif
