######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 8 20:21:45 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qdbus

# Input
HEADERS += client_adaptor.h skype_interface.h SkypeTrayIcon.h
SOURCES += client_adaptor.cpp \
           skype_interface.cpp \
           SkypeMsgStatus.cpp \
           SkypeTrayIcon.cpp
