/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i skype_interface.h -p skype_interface com.skype.api.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef SKYPE_INTERFACE_H_1190747328
#define SKYPE_INTERFACE_H_1190747328

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "skype_interface.h"

/*
 * Proxy class for interface com.Skype.API
 */
class ComSkypeAPIInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.Skype.API"; }

public:
    ComSkypeAPIInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComSkypeAPIInterface();

public Q_SLOTS: // METHODS
    inline QDBusReply<QString> Invoke(const QString &message)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(message);
        return callWithArgumentList(QDBus::Block, QLatin1String("Invoke"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace Skype {
    typedef ::ComSkypeAPIInterface API;
  }
}
#endif
